# CloudOrderX — Ansible Inventory
# Replace IP addresses with your actual host IPs or DNS names.

[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=~/.ssh/cloudorderx.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
project_name=cloudorderx
docker_compose_version=2.24.5

[app_servers]
app1  ansible_host=10.0.1.10
app2  ansible_host=10.0.1.11

[monitoring_servers]
monitor1 ansible_host=10.0.1.20

[app_servers:vars]
app_port=8080
node_env=production

[monitoring_servers:vars]
grafana_port=3000
prometheus_port=9090
